services:
  web:
    build: .
    env_file:
      - .env
    container_name: ${CONTAINER_WEB}
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${WEB_PORT}:5000"
    networks:
      - web-db-service_web-network

volumes:
  uploads:

networks:
  web-db-service_web-network:
    external: true